apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-k8s
  namespace: default
spec:
  selector:
    matchLabels:
      app: jenkins-k8s
  template:
    metadata:
      labels:
        app: jenkins-k8s
    spec:
      containers:
      - image: gaojila/jenkins-k8s:<BUILD_TAG>
        imagePullPolicy: IfNotPresent
        name: jenkins-k8s
